version: '3.9'

services:
  #MongoDB services
  mongo_db:
    container_name: mongo_container
    image: mongo:latest
    command: --quiet
    restart: always
    ports:
      - 2717:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_db:/data/db

  #Node API service 
  api:
    container_name: node_api
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_DB_URI: mongodb://mongo_db:27017/bookstore
      DB_NAME: bookstore
      NAME: MONGO
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
